/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jb_t508aq_pinpad_N20Epp */

#ifndef _Included_com_jb_t508aq_pinpad_N20Epp
#define _Included_com_jb_t508aq_pinpad_N20Epp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_open
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1open
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_check_conn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1check_1conn
  (JNIEnv *, jobject);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_inject_masterkey
 * Signature: (BB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1inject_1masterkey
  (JNIEnv *, jobject, jbyte, jbyte, jbyteArray, jint);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_inject_workkey
 * Signature: (BBBBB[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1inject_1workkey
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jbyte, jbyte, jbyteArray, jint);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_get_pinblock
 * Signature: (BSB[B[B[B[B[B[S)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1get_1pinblock
  (JNIEnv *, jobject, jbyte, jshort, jbyte, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jshortArray);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_get_mac
 * Signature: (B[BS[B)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1get_1mac
  (JNIEnv *, jobject, jbyte, jbyteArray, jshort, jbyteArray);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_encrypted_track
 * Signature: (B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1encrypted_1track
  (JNIEnv *, jobject, jbyte, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_confirm_amt
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1confirm_1amt
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_display_string
 * Signature: (III[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1display_1string
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1clear
  (JNIEnv *, jobject);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_jb_t508aq_pinpad_N20Epp
 * Method:    pinpad_get_string
 * Signature: (IIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_jb_t508aq_pinpad_N20Epp_pinpad_1get_1string
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
